baseURL = 'https://EMEEEEMMMM.github.io/'
languageCode = 'en-us'
title = 'My Blog'
theme = "hugo-theme-stack"

[params]
  author = "Bear Chen"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[taxonomies]
   category = "categories"
   tag = "tags"
